### ISSUE TITLE
20220321 github update

### ISSUE THREAD

**Issue by Wildertrek** [woz-u/DS-Student-Resources#30]
<img width="1336" alt="220321-DS-Team-Sched" src="https://user-images.githubusercontent.com/60656916/159384025-1e238df4-abd2-4677-a7e8-25dfd1447dc2.png">

**Comment by Wildertrek** [comment]
new schedule
<img width="1818" alt="20220527-Team-Schedulev3" src="https://user-images.githubusercontent.com/60656916/170761769-fa352bda-d650-4772-ae99-833014f5f17d.png">

**Comment by scarletging** [comment]
I don’t understand this email. 

Lauren Ravis

**Comment by Wildertrek** [comment]
It's just an update to the team schedule, thanks
